#!/bin/bash
del[0]="DROP TABLE IF EXISTS \`analysis\`;"
del[1]="CREATE TABLE \`analysis\` ("
del[2]="  \`analysisId\` int(11) NOT NULL AUTO_INCREMENT,"
del[3]="  \`run_date\` varchar(255) DEFAULT NULL,"
del[4]="  \`logic_name\` varchar(255) NOT NULL,"
del[5]="  \`parameters\` longtext,"
del[6]="  \`assembly_id\` int(11) NOT NULL,"
del[7]="  \`sample_id\` int(11) NOT NULL,"
del[8]="  PRIMARY KEY (\`analysisId\`),"
del[9]="  KEY \`FK_1r72v3obg8nrqab2n52ota3r2\` (\`assembly_id\`),"
del[10]="  KEY \`FK_7qm2opo97g2dosy849bhgsvqb\` (\`sample_id\`),"
del[11]="  CONSTRAINT \`FK_1r72v3obg8nrqab2n52ota3r2\` FOREIGN KEY (\`assembly_id\`) REFERENCES \`assembly\` (\`assembly_id\`),"
del[12]="  CONSTRAINT \`FK_7qm2opo97g2dosy849bhgsvqb\` FOREIGN KEY (\`sample_id\`) REFERENCES \`sample\` (\`sample_id\`)"
del[13]="DROP TABLE IF EXISTS \`assembly\`;"
del[14]="CREATE TABLE \`assembly\` ("
del[15]="  \`assembly_id\` int(11) NOT NULL AUTO_INCREMENT,"
del[16]="  \`assembly_accession\` varchar(255) NOT NULL,"
del[17]="  \`assembly_name\` varchar(255) NOT NULL,"
del[18]="  \`species_id\` int(11) DEFAULT NULL,"
del[19]="  PRIMARY KEY (\`assembly_id\`),"
del[20]="  UNIQUE KEY \`UK_9ph2yvfhc06pjuwvcjgtxejef\` (\`assembly_accession\`),"
del[21]="  KEY \`FK_okpj44x5yenw18r73xj8px4kf\` (\`species_id\`),"
del[22]="  CONSTRAINT \`FK_okpj44x5yenw18r73xj8px4kf\` FOREIGN KEY (\`species_id\`) REFERENCES \`species\` (\`taxon_id\`)"
del[23]="DROP TABLE IF EXISTS \`backsplice_junction\`;"
del[24]="CREATE TABLE \`backsplice_junction\` ("
del[25]="  \`junction_id\` int(11) NOT NULL AUTO_INCREMENT,"
del[26]="  \`browser_string\` longtext,"
del[27]="  \`coord_id\` varchar(255) DEFAULT NULL,"
del[28]="  \`genomic_size\` int(11) DEFAULT NULL,"
del[29]="  \`seq_region_end\` int(11) DEFAULT NULL,"
del[30]="  \`seq_region_name\` varchar(255) DEFAULT NULL,"
del[31]="  \`seq_region_start\` int(11) DEFAULT NULL,"
del[32]="  \`seq_region_strand\` varchar(255) DEFAULT NULL,"
del[33]="  \`JPM\` double DEFAULT NULL,"
del[34]="  \`abundance_ratio\` double DEFAULT NULL,"
del[35]="  \`predicted_exons\` varchar(255) DEFAULT NULL,"
del[36]="  \`raw_count\` int(11) DEFAULT NULL,"
del[37]="  \`splice_signal\` varchar(255) DEFAULT NULL,"
del[38]="  \`analysis_id\` int(11) NOT NULL,"
del[39]="  \`locus_id\` int(11) DEFAULT NULL,"
del[40]="  \`classification\` varchar(255) DEFAULT NULL,"
del[41]="  \`in_platelets\` bit(1) DEFAULT NULL,"
del[42]="  \`is_published\` bit(1) DEFAULT NULL,"
del[43]="  \`junction_repeat_coverage\` double DEFAULT NULL,"
del[44]="  \`n_methods\` int(11) DEFAULT NULL,"
del[45]="  \`splice_type\` varchar(255) DEFAULT NULL,"
del[46]="  \`spliced_size\` int(11) DEFAULT NULL,"
del[47]="  \`splice_3_support\` int(11) DEFAULT NULL,"
del[48]="  \`splice_5_support\` int(11) DEFAULT NULL,"
del[49]="  \`splice_site_count\` int(11) DEFAULT NULL,"
del[50]="  \`TPM\` double DEFAULT NULL,"
del[51]="  \`transcript_count\` double DEFAULT NULL,"
del[52]="  \`gc_perc\` double DEFAULT NULL,"
del[53]="  PRIMARY KEY (\`junction_id\`),"
del[54]="  KEY \`FK_7g3afyllcsldk5t9nd012hu93\` (\`locus_id\`),"
del[55]="  KEY \`FK_gdppp9c4041kpnv1wocvscs5j\` (\`analysis_id\`),"
del[56]="  CONSTRAINT \`FK_7g3afyllcsldk5t9nd012hu93\` FOREIGN KEY (\`locus_id\`) REFERENCES \`locus\` (\`locusId\`),"
del[57]="  CONSTRAINT \`FK_gdppp9c4041kpnv1wocvscs5j\` FOREIGN KEY (\`analysis_id\`) REFERENCES \`analysis\` (\`analysisId\`)"
del[58]="DROP TABLE IF EXISTS \`canonical_junction\`;"
del[59]="CREATE TABLE \`canonical_junction\` ("
del[60]="  \`junction_id\` int(11) NOT NULL AUTO_INCREMENT,"
del[61]="  \`browser_string\` longtext,"
del[62]="  \`coord_id\` varchar(255) DEFAULT NULL,"
del[63]="  \`genomic_size\` int(11) DEFAULT NULL,"
del[64]="  \`seq_region_end\` int(11) DEFAULT NULL,"
del[65]="  \`seq_region_name\` varchar(255) DEFAULT NULL,"
del[66]="  \`seq_region_start\` int(11) DEFAULT NULL,"
del[67]="  \`seq_region_strand\` varchar(255) DEFAULT NULL,"
del[68]="  \`JPM\` double DEFAULT NULL,"
del[69]="  \`predicted_exons\` varchar(255) DEFAULT NULL,"
del[70]="  \`raw_count\` int(11) DEFAULT NULL,"
del[71]="  \`splice_signal\` varchar(255) DEFAULT NULL,"
del[72]="  \`analysis_id\` int(11) NOT NULL,"
del[73]="  \`locus_id\` int(11) DEFAULT NULL,"
del[74]="  \`splice_type\` varchar(255) DEFAULT NULL,"
del[75]="  PRIMARY KEY (\`junction_id\`),"
del[76]="  KEY \`FK_8lpr7o5u75mklseeyamja334k\` (\`locus_id\`),"
del[77]="  KEY \`FK_lui5gi1tudm2da24k61bhfw3t\` (\`analysis_id\`),"
del[78]="  CONSTRAINT \`FK_8lpr7o5u75mklseeyamja334k\` FOREIGN KEY (\`locus_id\`) REFERENCES \`locus\` (\`locusId\`),"
del[79]="  CONSTRAINT \`FK_lui5gi1tudm2da24k61bhfw3t\` FOREIGN KEY (\`analysis_id\`) REFERENCES \`analysis\` (\`analysisId\`)"
del[80]="DROP TABLE IF EXISTS \`exon\`;"
del[81]="CREATE TABLE \`exon\` ("
del[82]="  \`locus_id\` int(11) NOT NULL,"
del[83]="  \`coord_id\` varchar(255) DEFAULT NULL,"
del[84]="  \`genomic_size\` int(11) DEFAULT NULL,"
del[85]="  \`seq_region_end\` int(11) DEFAULT NULL,"
del[86]="  \`seq_region_name\` varchar(255) DEFAULT NULL,"
del[87]="  \`seq_region_start\` int(11) DEFAULT NULL,"
del[88]="  \`seq_region_strand\` varchar(255) DEFAULT NULL,"
del[89]="  \`rank\` int(11) DEFAULT NULL,"
del[90]="  \`stable_id\` varchar(255) DEFAULT NULL,"
del[91]="  KEY \`FK_rn2bqjh4aik56jnrpagwh2br0\` (\`locus_id\`),"
del[92]="  CONSTRAINT \`FK_rn2bqjh4aik56jnrpagwh2br0\` FOREIGN KEY (\`locus_id\`) REFERENCES \`locus\` (\`locusId\`)"
del[93]=") ENGINE=InnoDB DEFAULT CHARSET=latin1;"
del[94]="DROP TABLE IF EXISTS \`hibernate_sequences\`;"
del[95]="CREATE TABLE \`hibernate_sequences\` ("
del[96]="  \`sequence_name\` varchar(255) DEFAULT NULL,"
del[97]="  \`sequence_next_hi_value\` int(11) DEFAULT NULL"
del[98]=") ENGINE=InnoDB DEFAULT CHARSET=latin1;"
del[99]="DROP TABLE IF EXISTS \`locus\`;"
del[100]="CREATE TABLE \`locus\` ("
del[101]="  \`locusId\` int(11) NOT NULL AUTO_INCREMENT,"
del[102]="  \`browser_string\` longtext,"
del[103]="  \`circrna_abundance_ratio\` double DEFAULT NULL,"
del[104]="  \`coord_id\` varchar(255) DEFAULT NULL,"
del[105]="  \`genomic_size\` int(11) DEFAULT NULL,"
del[106]="  \`seq_region_end\` int(11) DEFAULT NULL,"
del[107]="  \`seq_region_name\` varchar(255) DEFAULT NULL,"
del[108]="  \`seq_region_start\` int(11) DEFAULT NULL,"
del[109]="  \`seq_region_strand\` varchar(255) DEFAULT NULL,"
del[110]="  \`gene_name\` varchar(255) DEFAULT NULL,"
del[111]="  \`is_circrna_host\` bit(1) DEFAULT NULL,"
del[112]="  \`nexons\` int(11) DEFAULT NULL,"
del[113]="  \`source\` varchar(255) DEFAULT NULL,"
del[114]="  \`spliced_size\` int(11) DEFAULT NULL,"
del[115]="  \`stable_id\` varchar(255) DEFAULT NULL,"
del[116]="  \`total_backsplice_reads\` double DEFAULT NULL,"
del[117]="  \`total_splice_reads\` double DEFAULT NULL,"
del[118]="  \`assembly_id\` int(11) NOT NULL,"
del[119]="  PRIMARY KEY (\`locusId\`),"
del[120]="  KEY \`FK_kaidlko80rodyo94ulvw9dklf\` (\`assembly_id\`),"
del[121]="  CONSTRAINT \`FK_kaidlko80rodyo94ulvw9dklf\` FOREIGN KEY (\`assembly_id\`) REFERENCES \`assembly\` (\`assembly_id\`)"
del[122]="DROP TABLE IF EXISTS \`locus_expression\`;"
del[123]="CREATE TABLE \`locus_expression\` ("
del[124]="  \`expression_id\` int(11) NOT NULL AUTO_INCREMENT,"
del[125]="  \`deseq_normalised\` double DEFAULT NULL,"
del[126]="  \`FPKM\` double DEFAULT NULL,"
del[127]="  \`RPKM\` double DEFAULT NULL,"
del[128]="  \`rpkm_external\` double DEFAULT NULL,"
del[129]="  \`rpkm_internal\` double DEFAULT NULL,"
del[130]="  \`rpkm_ratio\` double DEFAULT NULL,"
del[131]="  \`TPM\` double DEFAULT NULL,"
del[132]="  \`analysis_id\` int(11) DEFAULT NULL,"
del[133]="  \`locus_id\` int(11) DEFAULT NULL,"
del[134]="  PRIMARY KEY (\`expression_id\`),"
del[135]="  KEY \`FK_1d965wkkt5my90lgewvafu43x\` (\`analysis_id\`),"
del[136]="  KEY \`FK_4vef6i1xkpngahbsf3jknsypt\` (\`locus_id\`),"
del[137]="  CONSTRAINT \`FK_1d965wkkt5my90lgewvafu43x\` FOREIGN KEY (\`analysis_id\`) REFERENCES \`analysis\` (\`analysisId\`),"
del[138]="  CONSTRAINT \`FK_4vef6i1xkpngahbsf3jknsypt\` FOREIGN KEY (\`locus_id\`) REFERENCES \`locus\` (\`locusId\`)"
del[139]=") ENGINE=InnoDB DEFAULT CHARSET=latin1;"
del[140]="DROP TABLE IF EXISTS \`sample\`;"
del[141]="CREATE TABLE \`sample\` ("
del[142]="  \`sample_id\` int(11) NOT NULL AUTO_INCREMENT,"
del[143]="  \`accession\` varchar(50) NOT NULL,"
del[144]="  \`backspliced_reads\` double DEFAULT NULL,"
del[145]="  \`chimeric_reads\` double DEFAULT NULL,"
del[146]="  \`circrna_count\` int(11) DEFAULT NULL,"
del[147]="  \`description\` longtext,"
del[148]="  \`fastqc_path\` varchar(255) DEFAULT NULL,"
del[149]="  \`ftp_path\` varchar(255) DEFAULT NULL,"
del[150]="  \`instrument\` varchar(100) DEFAULT NULL,"
del[151]="  \`library_size\` int(11) DEFAULT NULL,"
del[152]="  \`library_strategy\` varchar(255) DEFAULT NULL,"
del[153]="  \`gtag_cjuncs_reads\` double DEFAULT NULL,"
del[154]="  \`mapped_reads\` double DEFAULT NULL,"
del[155]="  \`read_length\` int(11) DEFAULT NULL,"
del[156]="  \`fraction\` varchar(100) DEFAULT NULL,"
del[157]="  \`submitter\` varchar(100) DEFAULT NULL,"
del[158]="  \`source\` varchar(50) DEFAULT NULL,"
del[159]="  \`total_spliced_reads\` double DEFAULT NULL,"
del[160]="  \`source_id\` int(11) DEFAULT NULL,"
del[161]="  PRIMARY KEY (\`sample_id\`),"
del[162]="  UNIQUE KEY \`UK_7ntygu84trwg1q88x2doa8m8e\` (\`accession\`),"
del[163]="  KEY \`FK_ffihengafhkia0btjoyrpptih\` (\`species_id\`),"
del[164]="  CONSTRAINT \`FK_ffihengafhkia0btjoyrpptih\` FOREIGN KEY (\`species_id\`) REFERENCES \`species\` (\`taxon_id\`)"
del[165]="DROP TABLE IF EXISTS \`species\`;"
del[166]="CREATE TABLE \`species\` ("
del[167]="  \`taxon_id\` int(11) NOT NULL,"
del[168]="  \`species_name\` varchar(255) DEFAULT NULL,"
del[169]="  PRIMARY KEY (\`taxon_id\`)"
del[170]=") ENGINE=InnoDB DEFAULT CHARSET=latin1;"
del[171]="DROP TABLE IF EXISTS \`ensembl_gene\`;"
del[172]="CREATE TABLE \`ensembl_gene\` ("
del[173]="  \`gene_id\` int(11) NOT NULL AUTO_INCREMENT,"
del[174]="  \`coord_id\` varchar(255) DEFAULT NULL,"
del[175]="  \`seq_region_end\` int(11) DEFAULT NULL,"
del[176]="  \`seq_region_name\` varchar(255) DEFAULT NULL,"
del[177]="  \`seq_region_start\` int(11) DEFAULT NULL,"
del[178]="  \`seq_region_strand\` varchar(255) DEFAULT NULL,"
del[179]="  \`gene_name\` varchar(255) DEFAULT NULL,"
del[180]="  \`description\` varchar(255) DEFAULT NULL,"
del[181]="  \`is_circrna_host\` bit(1) DEFAULT NULL,"
del[182]="  \`biotype\` varchar(255) DEFAULT NULL,"
del[183]="  \`stable_id\` varchar(255) DEFAULT NULL,"
del[184]="  \`assembly_id\` int(11) NOT NULL,"
del[185]="  PRIMARY KEY (\`gene_id\`),"
del[186]="  KEY \`assembly_id\` (\`assembly_id\`),"
del[187]="  CONSTRAINT \`ensembl_gene_ibfk_1\` FOREIGN KEY (\`assembly_id\`) REFERENCES \`assembly\` (\`assembly_id\`)"
del[188]="LOCK TABLES \`ensembl_gene\` WRITE;"
del[189]="  \`bigwig_path\` varchar(255) DEFAULT NULL,"
del[190]="  \`project\` varchar(255) DEFAULT NULL,"
del[191]="  \`TIN\` double DEFAULT NULL,"
del[192]="  \`raw_count\` double NOT NULL,"

addcore[0]="\`analysis\`"
addcore[1]="\`assembly\`"
addcore[2]="\`backsplice_junction\`"
addcore[3]="\`canonical_junction\`"
addcore[4]="\`exon\`"
addcore[5]="\`locus\`"
addcore[6]="\`locus_expression\`"
addcore[7]="\`sample\`"
addcore[8]="\`species\`"
addcore[9]="\`ensembl_gene\`"
addcore[10]="\`hibernate_sequences\`"

addedcore[0]="\`core_analysis\`"
addedcore[1]="\`core_assembly\`"
addedcore[2]="\`core_backsplicejunction\`"
addedcore[3]="\`core_canonicaljunction\`"
addedcore[4]="\`core_exon\`"
addedcore[5]="\`core_locus\`"
addedcore[6]="\`core_locusexpression\`"
addedcore[7]="\`core_sample\`"
addedcore[8]="\`core_species\`"
addedcore[9]="\`core_ensemblgene\`"
addedcore[10]="\`core_hibernatesequences\`"

tablemissingfields[0]="INSERT INTO \`core_analysis\` VALUES"
tablemissingfields[1]="INSERT INTO \`core_assembly\` VALUES"
tablemissingfields[2]="INSERT INTO \`core_backsplicejunction\` VALUES"
tablemissingfields[3]="INSERT INTO \`core_canonicaljunction\` VALUES"
tablemissingfields[4]="INSERT INTO \`core_exon\` VALUES"
tablemissingfields[5]="INSERT INTO \`core_locus\` VALUES"
tablemissingfields[6]="INSERT INTO \`core_locusexpression\` VALUES"
tablemissingfields[7]="INSERT INTO \`core_sample\` VALUES"
tablemissingfields[8]="INSERT INTO \`core_species\` VALUES"
tablemissingfields[9]="INSERT INTO \`core_ensemblgene\` VALUES"
tablemissingfields[10]="INSERT INTO \`core_hibernatesequences\` VALUES"

tableaddedfields[0]="INSERT INTO \`core_analysis\` (analysis_id, run_date, logic_name, parameters, assembly_id_id, sample_id_id) VALUES"
tableaddedfields[1]="INSERT INTO \`core_assembly\` (assembly_id, assembly_accession, assembly_name, species_id_id) VALUES"
tableaddedfields[2]="INSERT INTO \`core_backsplicejunction\` (junction_id, browser_string, coord_id, genomic_size, seq_region_end, seq_region_name, seq_region_start, seq_region_strand, jpm, abundance_ratio, predicted_exons, raw_count, splice_signal, analysis_id_id, locus_id_id, classification, in_platelets, is_published, junction_repeat_coverage, n_methods, splice_type, spliced_size, splice_3_support, splice_5_support, splice_site_count, tpm, transcript_count, gc_perc) VALUES"
tableaddedfields[3]="INSERT INTO \`core_canonicaljunction\` (junction_id, browser_string, coord_id, genomic_size, seq_region_end, seq_region_name, seq_region_start, seq_region_strand, jpm, predicted_exons, raw_count, splice_signal, analysis_id_id, locus_id_id, splice_type) VALUES"
tableaddedfields[4]="INSERT INTO \`core_exon\` (locus_id, coord_id, genomic_size, seq_region_end, seq_region_name, seq_region_start, seq_region_strand, rank, stable_id) VALUES"
tableaddedfields[5]="INSERT INTO \`core_locus\` (locus_id, browser_string, coord_id, genomic_size, seq_region_end, seq_region_name, seq_region_start, seq_region_strand, gene_name, is_circrna_host, nexons, source, spliced_size, stable_id, total_backsplice_reads, total_splice_reads, assembly_id_id, circrna_abundance_ratio, biotype) VALUES"
tableaddedfields[6]="INSERT INTO \`core_locusexpression\` (expression_id, raw_count, rpkm, rpkm_external, rpkm_internal, rpkm_ratio, tpm, analysis_id_id, locus_id_id) VALUES"
tableaddedfields[7]="INSERT INTO \`core_sample\` (sample_id, accession, backspliced_reads, chimeric_reads, circrna_count, description, fastqc_path, bigwig_path, ftp_path, instrument, library_size, library_strategy, project, gtag_cjuncs_reads, mapped_reads, read_length, fraction, submitter, source, total_spliced_reads, TIN, species_id_id, fastq_path, source_id) VALUES"
tableaddedfields[8]="INSERT INTO \`core_species\` (taxon_id, scientific_name) VALUES"
tableaddedfields[9]="INSERT INTO \`core_ensemblgene\` (gene_id, coord_id, seq_region_end, seq_region_name, seq_region_start, seq_region_strand, gene_name, description, is_circrna_host, biotype, stable_id, assembly_id_id) VALUES"
tableaddedfields[10]="INSERT INTO \`core_hibernatesequences\` (sequence_name, sequence_next_hi_value) VALUES"


# Delete create table statements
for index in ${!del[*]}
do
    sed -i "s|${del[$index]}.*||g" db.txt
    echo $index
done

sed -ri "s|\) ENGINE=InnoDB AUTO_INCREMENT=[0-9]+ DEFAULT CHARSET=latin1;||g" db.txt

# Change table names
for index in ${!addcore[*]}
do
    sed -i "s|${addcore[$index]}|${addedcore[$index]}|" db.txt
    echo $((index + 192))
done

# Change table field names
for index in ${!tablemissingfields[*]}
do
    sed -i "s|${tablemissingfields[$index]}|${tableaddedfields[$index]}|" db.txt
    echo $((index + 210))
done
