from core.models.species import Species
from core.models.assembly import Assembly
from core.models.sample import Sample
from core.models.analysis import Analysis
from core.models.locus import Locus
from core.models.exon import Exon
from core.models.locus_expression import LocusExpression
from core.models.canonical_junction import CanonicalJunction
from core.models.backsplice_junction import BackspliceJunction
