-- MySQL Script generated by MySQL Workbench
-- Friday 16 August 2019 09:53:13 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecircdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecircdb` ;

-- -----------------------------------------------------
-- Schema ecircdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecircdb` DEFAULT CHARACTER SET latin1 ;
USE `ecircdb` ;

-- -----------------------------------------------------
-- Table `ecircdb`.`core_species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecircdb`.`core_species` ;

CREATE TABLE IF NOT EXISTS `ecircdb`.`core_species` (
  `taxon_id` INT(11) NOT NULL AUTO_INCREMENT,
  `scientific_name` VARCHAR(127) NOT NULL,
  `common_name` VARCHAR(127) NULL DEFAULT NULL,
  `thumbnail` VARCHAR(100) NULL DEFAULT NULL,
  `description` LONGTEXT NOT NULL,
  PRIMARY KEY (`taxon_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10117
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecircdb`.`core_assembly`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecircdb`.`core_assembly` ;

CREATE TABLE IF NOT EXISTS `ecircdb`.`core_assembly` (
  `assembly_id` INT(11) NOT NULL AUTO_INCREMENT,
  `assembly_accession` VARCHAR(255) NOT NULL,
  `assembly_name` VARCHAR(255) NOT NULL,
  `assembly_genoverse_genome` VARCHAR(255) NOT NULL,
  `species_id_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`assembly_id`),
  INDEX `core_assembly_species_id_id_7b5c3c16_fk_core_species_taxon_id` (`species_id_id` ASC),
  CONSTRAINT `core_assembly_species_id_id_7b5c3c16_fk_core_species_taxon_id`
    FOREIGN KEY (`species_id_id`)
    REFERENCES `ecircdb`.`core_species` (`taxon_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecircdb`.`core_sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecircdb`.`core_sample` ;

CREATE TABLE IF NOT EXISTS `ecircdb`.`core_sample` (
  `sample_id` INT(11) NOT NULL AUTO_INCREMENT,
  `accession` VARCHAR(55) NOT NULL,
  `backspliced_reads` INT(11) NULL DEFAULT NULL,
  `chimeric_reads` INT(11) NULL DEFAULT NULL,
  `circrna_count` INT(11) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `fastqc_path` VARCHAR(255) NULL DEFAULT NULL,
  `bigwig_path` VARCHAR(255) NULL DEFAULT NULL,
  `ftp_path` VARCHAR(255) NULL DEFAULT NULL,
  `instrument` VARCHAR(103) NULL DEFAULT NULL,
  `library_size` INT(11) NULL DEFAULT NULL,
  `library_strategy` VARCHAR(255) NULL DEFAULT NULL,
  `project` VARCHAR(255) NULL DEFAULT NULL,
  `gtag_cjuncs_reads` INT(11) NULL DEFAULT NULL,
  `mapped_reads` INT(11) NULL DEFAULT NULL,
  `read_length` INT(11) NULL DEFAULT NULL,
  `fraction` VARCHAR(103) NULL DEFAULT NULL,
  `submitter` VARCHAR(103) NULL DEFAULT NULL,
  `source` VARCHAR(55) NULL DEFAULT NULL,
  `total_spliced_reads` INT(11) NULL DEFAULT NULL,
  `TIN` INT(11) NULL DEFAULT NULL,
  `species_id_id` INT(11) NULL DEFAULT NULL,
  `fastq_path` VARCHAR(255) NULL DEFAULT NULL,
  `source_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`sample_id`),
  INDEX `core_sample_species_id_id_c6f049f6_fk_core_species_taxon_id` (`species_id_id` ASC),
  CONSTRAINT `core_sample_species_id_id_c6f049f6_fk_core_species_taxon_id`
    FOREIGN KEY (`species_id_id`)
    REFERENCES `ecircdb`.`core_species` (`taxon_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 923
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecircdb`.`core_analysis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecircdb`.`core_analysis` ;

CREATE TABLE IF NOT EXISTS `ecircdb`.`core_analysis` (
  `analysis_id` INT(11) NOT NULL AUTO_INCREMENT,
  `run_date` VARCHAR(255) NOT NULL,
  `logic_name` VARCHAR(255) NOT NULL,
  `parameters` VARCHAR(103) NULL DEFAULT NULL,
  `assembly_id_id` INT(11) NOT NULL,
  `sample_id_id` INT(11) NOT NULL,
  PRIMARY KEY (`analysis_id`),
  INDEX `core_analysis_assembly_id_id_e390aed0_fk_core_asse` (`assembly_id_id` ASC),
  INDEX `core_analysis_sample_id_id_975f722e_fk_core_sample_sample_id` (`sample_id_id` ASC),
  CONSTRAINT `core_analysis_assembly_id_id_e390aed0_fk_core_asse`
    FOREIGN KEY (`assembly_id_id`)
    REFERENCES `ecircdb`.`core_assembly` (`assembly_id`),
  CONSTRAINT `core_analysis_sample_id_id_975f722e_fk_core_sample_sample_id`
    FOREIGN KEY (`sample_id_id`)
    REFERENCES `ecircdb`.`core_sample` (`sample_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1035
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecircdb`.`core_locus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecircdb`.`core_locus` ;

CREATE TABLE IF NOT EXISTS `ecircdb`.`core_locus` (
  `locus_id` INT(11) NOT NULL AUTO_INCREMENT,
  `browser_string` LONGTEXT NOT NULL,
  `circrna_abundance_ratio` DECIMAL(19,6) NULL DEFAULT NULL,
  `coord_id` VARCHAR(255) NULL DEFAULT NULL,
  `genomic_size` INT(11) NULL DEFAULT NULL,
  `seq_region_end` INT(11) NULL DEFAULT NULL,
  `seq_region_name` VARCHAR(255) NULL DEFAULT NULL,
  `seq_region_start` INT(11) NULL DEFAULT NULL,
  `seq_region_strand` VARCHAR(255) NULL DEFAULT NULL,
  `gene_name` VARCHAR(255) NULL DEFAULT NULL,
  `is_circrna_host` TINYINT(1) NULL DEFAULT NULL,
  `nexons` INT(11) NULL DEFAULT NULL,
  `source` VARCHAR(255) NULL DEFAULT NULL,
  `spliced_size` INT(11) NULL DEFAULT NULL,
  `stable_id` VARCHAR(255) NULL DEFAULT NULL,
  `total_backsplice_reads` INT(11) NULL DEFAULT NULL,
  `total_splice_reads` INT(11) NULL DEFAULT NULL,
  `biotype` VARCHAR(255) NULL DEFAULT NULL,
  `assembly_id_id` INT(11) NOT NULL,
  PRIMARY KEY (`locus_id`),
  INDEX `core_locus_assembly_id_id_b22709ef_fk_core_assembly_assembly_id` (`assembly_id_id` ASC),
  CONSTRAINT `core_locus_assembly_id_id_b22709ef_fk_core_assembly_assembly_id`
    FOREIGN KEY (`assembly_id_id`)
    REFERENCES `ecircdb`.`core_assembly` (`assembly_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1086531
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecircdb`.`core_backsplicejunction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecircdb`.`core_backsplicejunction` ;

CREATE TABLE IF NOT EXISTS `ecircdb`.`core_backsplicejunction` (
  `junction_id` INT(11) NOT NULL AUTO_INCREMENT,
  `browser_string` LONGTEXT NULL DEFAULT NULL,
  `coord_id` VARCHAR(255) NULL DEFAULT NULL,
  `genomic_size` INT(11) NULL DEFAULT NULL,
  `seq_region_end` INT(11) NULL DEFAULT NULL,
  `seq_region_name` VARCHAR(255) NULL DEFAULT NULL,
  `seq_region_start` INT(11) NULL DEFAULT NULL,
  `seq_region_strand` VARCHAR(255) NULL DEFAULT NULL,
  `jpm` DECIMAL(19,6) NULL DEFAULT NULL,
  `predicted_exons` VARCHAR(255) NULL DEFAULT NULL,
  `raw_count` INT(11) NULL DEFAULT NULL,
  `splice_signal` INT(11) NULL DEFAULT NULL,
  `classification` VARCHAR(255) NULL DEFAULT NULL,
  `in_platelets` TINYINT(1) NULL DEFAULT NULL,
  `is_published` TINYINT(1) NULL DEFAULT NULL,
  `junction_repeat_coverage` INT(11) NULL DEFAULT NULL,
  `n_methods` INT(11) NULL DEFAULT NULL,
  `spliced_size` INT(11) NULL DEFAULT NULL,
  `splice_type` VARCHAR(255) NULL DEFAULT NULL,
  `splice_3_support` INT(11) NULL DEFAULT NULL,
  `splice_5_support` INT(11) NULL DEFAULT NULL,
  `splice_site_count` INT(11) NULL DEFAULT NULL,
  `tpm` DECIMAL(19,6) NULL DEFAULT NULL,
  `transcript_count` DECIMAL(19,6) NULL DEFAULT NULL,
  `gc_perc` DECIMAL(19,6) NULL DEFAULT NULL,
  `abundance_ratio` DECIMAL(19,6) NULL DEFAULT NULL,
  `analysis_id_id` INT(11) NOT NULL,
  `locus_id_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`junction_id`),
  INDEX `core_backsplicejunct_analysis_id_id_895c5474_fk_core_anal` (`analysis_id_id` ASC),
  INDEX `core_backsplicejunct_locus_id_id_13fff60d_fk_core_locu` (`locus_id_id` ASC),
  CONSTRAINT `core_backsplicejunct_analysis_id_id_895c5474_fk_core_anal`
    FOREIGN KEY (`analysis_id_id`)
    REFERENCES `ecircdb`.`core_analysis` (`analysis_id`),
  CONSTRAINT `core_backsplicejunct_locus_id_id_13fff60d_fk_core_locu`
    FOREIGN KEY (`locus_id_id`)
    REFERENCES `ecircdb`.`core_locus` (`locus_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38408
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecircdb`.`core_canonicaljunction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecircdb`.`core_canonicaljunction` ;

CREATE TABLE IF NOT EXISTS `ecircdb`.`core_canonicaljunction` (
  `junction_id` INT(11) NOT NULL AUTO_INCREMENT,
  `browser_string` LONGTEXT NULL DEFAULT NULL,
  `coord_id` VARCHAR(255) NULL DEFAULT NULL,
  `genomic_size` INT(11) NULL DEFAULT NULL,
  `seq_region_end` INT(11) NULL DEFAULT NULL,
  `seq_region_name` VARCHAR(255) NULL DEFAULT NULL,
  `seq_region_start` INT(11) NULL DEFAULT NULL,
  `seq_region_strand` VARCHAR(255) NULL DEFAULT NULL,
  `jpm` DECIMAL(19,6) NULL DEFAULT NULL,
  `predicted_exons` VARCHAR(255) NULL DEFAULT NULL,
  `raw_count` INT(11) NULL DEFAULT NULL,
  `splice_signal` INT(11) NULL DEFAULT NULL,
  `splice_type` VARCHAR(255) NULL DEFAULT NULL,
  `analysis_id_id` INT(11) NOT NULL,
  `locus_id_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`junction_id`),
  INDEX `core_canonicaljuncti_analysis_id_id_a77c1e51_fk_core_anal` (`analysis_id_id` ASC),
  INDEX `core_canonicaljuncti_locus_id_id_91a79724_fk_core_locu` (`locus_id_id` ASC),
  CONSTRAINT `core_canonicaljuncti_analysis_id_id_a77c1e51_fk_core_anal`
    FOREIGN KEY (`analysis_id_id`)
    REFERENCES `ecircdb`.`core_analysis` (`analysis_id`),
  CONSTRAINT `core_canonicaljuncti_locus_id_id_91a79724_fk_core_locu`
    FOREIGN KEY (`locus_id_id`)
    REFERENCES `ecircdb`.`core_locus` (`locus_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4158084
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecircdb`.`core_ensemblgene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecircdb`.`core_ensemblgene` ;

CREATE TABLE IF NOT EXISTS `ecircdb`.`core_ensemblgene` (
  `gene_id` INT(11) NOT NULL AUTO_INCREMENT,
  `coord_id` VARCHAR(255) NULL DEFAULT NULL,
  `seq_region_end` INT(11) NULL DEFAULT NULL,
  `seq_region_name` VARCHAR(255) NULL DEFAULT NULL,
  `seq_region_start` INT(11) NULL DEFAULT NULL,
  `seq_region_strand` VARCHAR(255) NULL DEFAULT NULL,
  `gene_name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `is_circrna_host` TINYINT(1) NULL DEFAULT NULL,
  `biotype` VARCHAR(255) NULL DEFAULT NULL,
  `stable_id` VARCHAR(255) NULL DEFAULT NULL,
  `assembly_id_id` INT(11) NOT NULL,
  PRIMARY KEY (`gene_id`),
  INDEX `core_ensemblgene_assembly_id_id_f2ba8c34_fk_core_asse` (`assembly_id_id` ASC),
  CONSTRAINT `core_ensemblgene_assembly_id_id_f2ba8c34_fk_core_asse`
    FOREIGN KEY (`assembly_id_id`)
    REFERENCES `ecircdb`.`core_assembly` (`assembly_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 294048
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecircdb`.`core_exon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecircdb`.`core_exon` ;

CREATE TABLE IF NOT EXISTS `ecircdb`.`core_exon` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `coord_id` VARCHAR(255) NULL DEFAULT NULL,
  `genomic_size` INT(11) NULL DEFAULT NULL,
  `seq_region_end` INT(11) NULL DEFAULT NULL,
  `seq_region_name` VARCHAR(255) NULL DEFAULT NULL,
  `seq_region_start` INT(11) NULL DEFAULT NULL,
  `seq_region_strand` VARCHAR(255) NULL DEFAULT NULL,
  `rank` INT(11) NULL DEFAULT NULL,
  `stable_id` VARCHAR(255) NULL DEFAULT NULL,
  `locus_id_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `core_exon_locus_id_id_c1813ee5_fk_core_locus_locus_id` (`locus_id_id` ASC),
  CONSTRAINT `core_exon_locus_id_id_c1813ee5_fk_core_locus_locus_id`
    FOREIGN KEY (`locus_id_id`)
    REFERENCES `ecircdb`.`core_locus` (`locus_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecircdb`.`core_locusexpression`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecircdb`.`core_locusexpression` ;

CREATE TABLE IF NOT EXISTS `ecircdb`.`core_locusexpression` (
  `expression_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rpkm` DECIMAL(19,6) NULL DEFAULT NULL,
  `rpkm_external` DECIMAL(19,6) NULL DEFAULT NULL,
  `rpkm_internal` DECIMAL(19,6) NULL DEFAULT NULL,
  `rpkm_ratio` DECIMAL(19,6) NULL DEFAULT NULL,
  `raw_count` INT(11) NULL DEFAULT NULL,
  `tpm` DECIMAL(19,6) NULL DEFAULT NULL,
  `analysis_id_id` INT(11) NULL DEFAULT NULL,
  `locus_id_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`expression_id`),
  INDEX `core_locusexpression_analysis_id_id_6cbe7a68_fk_core_anal` (`analysis_id_id` ASC),
  INDEX `core_locusexpression_locus_id_id_a32b9846_fk_core_locus_locus_id` (`locus_id_id` ASC),
  CONSTRAINT `core_locusexpression_analysis_id_id_6cbe7a68_fk_core_anal`
    FOREIGN KEY (`analysis_id_id`)
    REFERENCES `ecircdb`.`core_analysis` (`analysis_id`),
  CONSTRAINT `core_locusexpression_locus_id_id_a32b9846_fk_core_locus_locus_id`
    FOREIGN KEY (`locus_id_id`)
    REFERENCES `ecircdb`.`core_locus` (`locus_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 492937
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
